<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class UserStudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $students = [
            [
                'id' => 20,
                'name' => 'Nguyễn Văn Anh',
                'email' => 'nguyenvananh@gmail.com',
                'phone' => '0901234567',
                'bio' => 'Sinh viên năm 3 Công nghệ thông tin, đam mê lập trình web và mobile app.',
                'password' => Hash::make('123456'),
                'role' => 'student',
                'is_active' => true,
                'email_verified_at' => Carbon::now(),
                'last_login_at' => Carbon::now()->subDays(1),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 21,
                'name' => 'Trần Thị Bình',
                'email' => 'tranthibinh@gmail.com',
                'phone' => '0912345678',
                'bio' => 'Mới tốt nghiệp, muốn học thêm về Laravel và Vue.js để tìm việc.',
                'password' => Hash::make('123456'),
                'role' => 'student',
                'is_active' => true,
                'email_verified_at' => Carbon::now(),
                'last_login_at' => Carbon::now()->subDays(2),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 22,
                'name' => 'Lê Minh Cường',
                'email' => 'leminhcuong@gmail.com',
                'phone' => '0923456789',
                'bio' => 'Lập trình viên junior, muốn nâng cao kỹ năng PHP và database.',
                'password' => Hash::make('123456'),
                'role' => 'student',
                'is_active' => true,
                'email_verified_at' => Carbon::now(),
                'last_login_at' => Carbon::now()->subHours(3),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 23,
                'name' => 'Phạm Thị Dung',
                'email' => 'phamthidung@gmail.com',
                'phone' => '0934567890',
                'bio' => 'Kế toán chuyển nghề sang IT, đang học lập trình từ cơ bản.',
                'password' => Hash::make('123456'),
                'role' => 'student',
                'is_active' => true,
                'email_verified_at' => Carbon::now(),
                'last_login_at' => Carbon::now()->subDays(3),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 24,
                'name' => 'Hoàng Văn Em',
                'email' => 'hoangvanem@gmail.com',
                'phone' => '0945678901',
                'bio' => 'Sinh viên năm 2 CNTT, yêu thích machine learning và AI.',
                'password' => Hash::make('123456'),
                'role' => 'student',
                'is_active' => true,
                'email_verified_at' => Carbon::now(),
                'last_login_at' => Carbon::now()->subDays(1),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 25,
                'name' => 'Vũ Thị Hoa',
                'email' => 'vuthihoa@gmail.com',
                'phone' => '0956789012',
                'bio' => 'Freelancer, muốn học thêm về React và Node.js.',
                'password' => Hash::make('123456'),
                'role' => 'student',
                'is_active' => true,
                'email_verified_at' => Carbon::now(),
                'last_login_at' => Carbon::now()->subHours(5),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 26,
                'name' => 'Đỗ Minh Giang',
                'email' => 'dominggiang@gmail.com',
                'phone' => '0967890123',
                'bio' => 'Developer có 2 năm kinh nghiệm, muốn học thêm về DevOps.',
                'password' => Hash::make('123456'),
                'role' => 'student',
                'is_active' => true,
                'email_verified_at' => Carbon::now(),
                'last_login_at' => Carbon::now()->subDays(2),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 27,
                'name' => 'Bùi Thị Hương',
                'email' => 'buithihuong@gmail.com',
                'phone' => '0978901234',
                'bio' => 'Tester muốn chuyển sang automation testing và lập trình.',
                'password' => Hash::make('123456'),
                'role' => 'student',
                'is_active' => true,
                'email_verified_at' => Carbon::now(),
                'last_login_at' => Carbon::now()->subDays(4),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 28,
                'name' => 'Ngô Văn Khoa',
                'email' => 'ngovankhoa@gmail.com',
                'phone' => '0989012345',
                'bio' => 'Sinh viên năm 4, chuẩn bị luận văn về web application.',
                'password' => Hash::make('123456'),
                'role' => 'student',
                'is_active' => true,
                'email_verified_at' => Carbon::now(),
                'last_login_at' => Carbon::now()->subHours(2),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 29,
                'name' => 'Đinh Thị Lan',
                'email' => 'dinhthilan@gmail.com',
                'phone' => '0990123456',
                'bio' => 'Marketing muốn học code để hiểu rõ hơn về sản phẩm công ty.',
                'password' => Hash::make('123456'),
                'role' => 'student',
                'is_active' => true,
                'email_verified_at' => Carbon::now(),
                'last_login_at' => Carbon::now()->subDays(1),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 30,
                'name' => 'Lý Văn Minh',
                'email' => 'lyvanminh@gmail.com',
                'phone' => '0901234560',
                'bio' => 'Fullstack developer muốn học thêm về microservices.',
                'password' => Hash::make('123456'),
                'role' => 'student',
                'is_active' => true,
                'email_verified_at' => Carbon::now(),
                'last_login_at' => Carbon::now()->subHours(1),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 31,
                'name' => 'Trương Thị Nga',
                'email' => 'truongthinga@gmail.com',
                'phone' => '0912345671',
                'bio' => 'Sinh viên năm 1, mới bắt đầu học lập trình.',
                'password' => Hash::make('123456'),
                'role' => 'student',
                'is_active' => true,
                'email_verified_at' => Carbon::now(),
                'last_login_at' => Carbon::now()->subDays(3),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 32,
                'name' => 'Phan Văn Ơn',
                'email' => 'phanvanon@gmail.com',
                'phone' => '0923456782',
                'bio' => 'Backend developer quan tâm đến performance và scalability.',
                'password' => Hash::make('123456'),
                'role' => 'student',
                'is_active' => true,
                'email_verified_at' => Carbon::now(),
                'last_login_at' => Carbon::now()->subDays(2),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 33,
                'name' => 'Cao Thị Phương',
                'email' => 'caothiphuong@gmail.com',
                'phone' => '0934567893',
                'bio' => 'UX/UI designer muốn học frontend để implement design.',
                'password' => Hash::make('123456'),
                'role' => 'student',
                'is_active' => true,
                'email_verified_at' => Carbon::now(),
                'last_login_at' => Carbon::now()->subHours(6),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 34,
                'name' => 'Võ Văn Quang',
                'email' => 'vovanquang@gmail.com',
                'phone' => '0945678904',
                'bio' => 'System admin muốn học về cloud computing và containerization.',
                'password' => Hash::make('123456'),
                'role' => 'student',
                'is_active' => true,
                'email_verified_at' => Carbon::now(),
                'last_login_at' => Carbon::now()->subDays(1),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 35,
                'name' => 'Đặng Thị Rằm',
                'email' => 'dangthiram@gmail.com',
                'phone' => '0956789015',
                'bio' => 'Sinh viên part-time, vừa học vừa làm để có kinh nghiệm thực tế.',
                'password' => Hash::make('123456'),
                'role' => 'student',
                'is_active' => true,
                'email_verified_at' => Carbon::now(),
                'last_login_at' => Carbon::now()->subDays(5),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 36,
                'name' => 'Huỳnh Văn Sơn',
                'email' => 'huynhvanson@gmail.com',
                'phone' => '0967890126',
                'bio' => 'Mobile developer muốn học thêm về cross-platform development.',
                'password' => Hash::make('123456'),
                'role' => 'student',
                'is_active' => true,
                'email_verified_at' => Carbon::now(),
                'last_login_at' => Carbon::now()->subHours(4),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 37,
                'name' => 'Lại Thị Tâm',
                'email' => 'laithitam@gmail.com',
                'phone' => '0978901237',
                'bio' => 'Data analyst muốn học thêm về machine learning và Python.',
                'password' => Hash::make('123456'),
                'role' => 'student',
                'is_active' => true,
                'email_verified_at' => Carbon::now(),
                'last_login_at' => Carbon::now()->subDays(3),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 38,
                'name' => 'Mạc Văn Uy',
                'email' => 'macvanuy@gmail.com',
                'phone' => '0989012348',
                'bio' => 'Fresher developer muốn nâng cao kỹ năng và kiến thức chuyên môn.',
                'password' => Hash::make('123456'),
                'role' => 'student',
                'is_active' => true,
                'email_verified_at' => Carbon::now(),
                'last_login_at' => Carbon::now()->subDays(1),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 39,
                'name' => 'Ông Thị Vân',
                'email' => 'ongthivan@gmail.com',
                'phone' => '0990123459',
                'bio' => 'Sinh viên năm cuối, muốn học thêm để chuẩn bị cho môi trường làm việc.',
                'password' => Hash::make('123456'),
                'role' => 'student',
                'is_active' => true,
                'email_verified_at' => Carbon::now(),
                'last_login_at' => Carbon::now()->subHours(7),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        // Insert dữ liệu vào bảng users
        DB::table('users')->insert($students);
    }
}
